#! /bin/sh

wal -R &
. "${HOME}/.cache/wal/colors.sh"

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-0 -d I II III IV V
bspc monitor HDMI-0 -d VI VII VIII IX X



setxkbmap -model pc105 -layout us,ru -variant qwerty, -option grp:alt_shift_toggle

bspc config border_width         2
bspc config window_gap          15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

# moving floating windows and resize them with mouse, hold alt key
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner


# dual monitors setup
~/.screenlayout/display.sh &

# wallpaper and polybar setup
~/.config/random_wallpaper/random.sh &

# start compositor
picom &

# autostart
flameshot &
